name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10, 12]
    steps:
    - uses: actions/checkout@v2
    - name: Set up node ${{ matrix.node-version }} using nvm
      uses: dcodeIO/setup-node-nvm@v2.0.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Resolve IPv6 addresses
      run: |
        node -p 'require("dns").getServers()'
        echo 'lookup loopback6.unittest.grpc.io hints: 0'
        node -p 'require("dns").lookup("loopback6.unittest.grpc.io", {all: true, hints: 0}, console.log)'
        echo 'lookup loopback6.unittest.grpc.io hints: dns.V4MAPPED'
        node -p 'require("dns").lookup("loopback6.unittest.grpc.io", {all: true, hints: dns.V4MAPPED}, console.log)'
        echo 'resolve loopback6.unittest.grpc.io'
        node -p 'require("dns").resolve6("loopback6.unittest.grpc.io", console.log)'
        host loopback6.unittest.grpc.io
        node -p 'require("dns").lookup("loopback46.unittest.grpc.io", {all: true, hints: dns.V4MAPPED}, console.log)'
        host loopback46.unittest.grpc.io
    - name: Install dependencies
      run: |
        npm install
        npm install -g gulp
    - name: Run pure JS tests
      run: |
        npm install
        gulp test
      working-directory: packages/grpc-js
